### ISSUE TITLE
Complete the table using the data from the PDF file

### ISSUE THREAD

**Issue by ivanvartanyan** [paramatma-team/gopaljiu#1]
We need to complete the table of Books, Booklets, etc. using information we have in attached PDF files. All missing information (including actual prices) should be requested by Ivan from Madhavananda Prabhu.

Необходимо заполнить таблицу с книгами, буклетами итд. используя имеющуюся по ним информацию в прикрепленных PDF файлах. Некоторой информации будет не хватать, необходимо проверить ее наличие на сайте http://gopaljiu.org и если и там ничего нет, то просто пропускать. Я запрошу всю недостающую информацию у Мадхавананды Прабху после первичного заполнения таблицы. При переносе текста из PDF файлов сначала следует копировать текст в простой текстовый редактор типа Gedit, Leafpad, Mousepad и убирать ненужные переносы строк и прочий мусор, а потом только копировать в таблицу в экселе.

[Books catalog 2009.pdf](https://github.com/paramatma-team/gopaljiu/files/34862/Books.catalog.2009.pdf)
[Magazines catalog 2009.pdf](https://github.com/paramatma-team/gopaljiu/files/34863/Magazines.catalog.2009.pdf)
[GopalJiu Publications Full Catalog (editor version).xlsx](https://github.com/paramatma-team/gopaljiu/files/34865/GopalJiu.Publications.Full.Catalog.editor.version.xlsx)

**Comment by amakhov108** [comment]
Hare Krishna Ivan prabhu! The following Gopal Jiu Publications Full Catalog contains actual informations about all items (books, booklets, magazines, cd's) purchased in the shop. There are some "wholes" in this catalog as I didn't found any information about some items. They are marked as empty cells in the catalog.
[GopalJiu.Publications.Full.Catalog.editor.version.xlsx](https://github.com/paramatma-team/gopaljiu/files/37785/GopalJiu.Publications.Full.Catalog.editor.version.xlsx)
